### ISSUE TITLE
Add link to user manual

### ISSUE THREAD

**Issue by benburwell** [MCEMS/dispatch#11]
Dispatchers should be able to click on a "Help" link to see the user manual.

**Comment by victorlora** [comment]
I'll work on this later today

**Comment by EliRuss** [comment]
@vlora95, the Closed Executive Board will likely have additional suggestions to make after we meet today.

**Comment by benburwell** [comment]
Okay, changes to the manual won't actually affect this issue, as the link will not change. However, if there are changes that need to be made to the manual, please open a new issue for the change. Thanks!

**Comment by victorlora** [comment]
Done in 52f73e2

**Comment by EliRuss** [comment]
@victorlora, how can this feature be viewed now?

**Comment by benburwell** [comment]
It looks like that extra button is still up in the menu bar. Can you remove it? Thanks!
