### ISSUE TITLE
Daytime Response Rollout Timeline

### ISSUE THREAD

**Issue by EliRuss** [MCEMS/dispatch#14]
Hi, @benburwell @jmankhan @NewtonianBrown et al,

We have all worked hard to get to where we with Daytime Response. As we know, more work is needed to launch MCEMS into 24-Hour Service.

Please review a timeline I have drafted to bring Daytime Response to a reality. This document will be continually updated, and will be reviewed tonight by the Closed Executive Board, and from there will be passed along to our Advisors. Please let me know if you have any issues, comments, or suggestions.

https://docs.google.com/document/d/1SZS2hIeLRmm31GObaaku1SekZxkv23oatB2rccg3VF8/edit

**Comment by benburwell** [comment]
Do you want to include paying for Heroku? That's the $7/month to keep the server alive 24/7.

**Comment by EliRuss** [comment]
@benburwell We are interested, currently figuring out a way to pay for it, though. Thanks for the reminder, I added it to the Timeline.

**Comment by benburwell** [comment]
Okay. As this doesn't appear to require any further action on our part that is not documented elsewhere, I'm going to close this issue.
