### ISSUE TITLE
Minor edits 1/7/16

### ISSUE THREAD

**Issue by EliRuss** [MCEMS/dispatch#20]
The Closed E-Board changed "PickUp" to "Avail" (though this may change in the future). Additionally, we have enabled "Discard Watch Responses". Will these changes affect anything on the website side of things?

**Comment by benburwell** [comment]
Discard watch responses is actually helpful -- I was manually filtering them out for the purposes of the dispatch console, so now I can remove that. The only thing that changing PickUp to Avail should affect is the color coding -- is there a color you'd like Avail to be listed as?

Also, I may have been a bit misleading when I said to make sure people set themselves to Clear -- they should only do this if they previously had a different status -- shouldn't Clear yourself from a call that you were never responding to, as that would result in the dispatcher having to weed through tons of Clears for each call.

Let me know if there's a text style you'd like for Avail?

**Comment by EliRuss** [comment]
Yes, that is the procedure we have in place for "Clear." 

Feel free to make the colors as you see fit, but in my mind "Resp" should be red.

**Comment by benburwell** [comment]
Okay. The only reason I mentioned it is because I saw a bunch of people had marked themselves Clear on the test alerts I needed to send out the other day.

I'll make Resp red :)

**Comment by EliRuss** [comment]
Yes, I noticed that, too. We have not done any sort of training or orientation just yet but after we do hopefully that won't be the case. Thank you!

**Comment by EliRuss** [comment]
Hi Ben, sorry for the change, but the Line Officers sat down and decided these are our response options (in order) and the colors we would like for them: 
Resp - Black (bolded)
Driver - light blue (bolded)
OnScen - Green (bolded)
Clear - Heather grey (non-bolded)
Sprvsr - Red (non-bolded)

**Comment by benburwell** [comment]
@eliruss, Jalal has pushed this enhancement to production. Could you verify that it meets your requirements? Thanks!

**Comment by EliRuss** [comment]
We like it! Can we make the blue a little darker (perhaps a royal blue) and the green a little less bright so it contrasts better with the white background and is easier to see?

**Comment by jmankhan** [comment]
I can do that, but it might be easier to pick out the exact colors beforehand so we don't have to keep updating the source code. 

If you like [#4169e1](http://www.color-hex.com/color/4169e1) for the blue, and [#006600](http://www.color-hex.com/color/006600) for the green, I can put them in. If you want something a little bit different, get me the hex color and I'll put them in

Thanks

**Comment by benburwell** [comment]
I like the blue, let's go with #090 for the green though. Thanks!

**Comment by jmankhan** [comment]
Done

**Comment by benburwell** [comment]
Okay, great. @EliRuss, I'm going to close this for now. Please reopen or create a new issue if you'd like additional changes. Thanks!
