### ISSUE TITLE
Non-responsiveness of Response Options

### ISSUE THREAD

**Issue by EliRuss** [MCEMS/dispatch#21]
Conducted testing today with Campus Safety. After I selected "Resp" I showed up on the console, but when I selected "OnScen" this update did not appear.

**Comment by benburwell** [comment]
@eliruss, did it show up in the app? Did you wait at least a minute? Also, do you remember what call this was for?

**Comment by EliRuss** [comment]
Yes, it showed up in the app. Although, in one case, I did have to select the same option twice because it did not register the first time. We waited several minutes. This happened on all of the test calls conducted today.

**Comment by benburwell** [comment]
Closing as a duplicate of #22 -- see comments there.
